version: "3.7"

services:
  debt_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRESS_DB: postgres
  django:
    container_name: debitors
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/debt/manage.py migrate --noinput &&
             python /usr/src/debt/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/debt
    ports:
      - 8000:8000
    depends_on:
      - debt_db
volumes:
  postgres_data: