# Generated by Django 3.2.5 on 2021-08-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectNumber', models.CharField(db_index=True, max_length=150, verbose_name='Наименование проекта')),
                ('statusProject', models.CharField(choices=[('Активный', 'Активный'), ('Завершенный', 'Завершенный')], max_length=250, verbose_name='Статус проекта')),
                ('category', models.CharField(db_index=True, max_length=150, verbose_name='Категория долга:')),
                ('amountDebts', models.IntegerField(db_index=True, verbose_name='Номинал долга:')),
                ('amountRecovery', models.IntegerField(db_index=True, verbose_name='Плановая сумма взыскания:')),
                ('amountBye', models.IntegerField(db_index=True, verbose_name='Сумма покупки:')),
                ('amountCosts', models.IntegerField(db_index=True, verbose_name='Плановая сумма расходов:')),
                ('expectedReturn', models.IntegerField(db_index=True, verbose_name='Ожидаемая годовая доходность:')),
                ('amountInvestment', models.IntegerField(db_index=True, verbose_name='Сумма инвестиций:')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
